### PR TITLE
Modify status to Used/Unused

### PR DESCRIPTION
**Pull request by ReedyChen**

### CODE REVIEW

**Comment by HerlinHe** [comment]
So you set an attribute to show if a promotion is used or not. In my perspective, what you mean is, when customers use one promotion, then it is invalid and cannot be used by other customers, right?

**Comment by ReedyChen** [comment]
I am thinking something like the ubereats promo codes, once it's redeemed and other people will not be allowed to use it.

**Comment by HerlinHe** [comment]
But we don't have an attribute called "code" or redeem function. In the ubereats scenario, the promotion is created for "user", not "food". The model of our project is more like a traditional promotion for an e-shop website so that one promotion is for one kind of product, and we have "product_id", and "product_name" to show the relationship. In this case, suppose we have 10000 customers who want to buy the same product, then we need to create more than 10000 data in our database to represent the identical promotion for the same product, which is kind of a waste of resources.

**Comment by HerlinHe** [comment]
I know you have spent a lot of time on this issue. But if we want to add a new feature, we need to discuss it with other teammates before starting the work. I think we achieved a consensus to add an attribute "available" (or "expire" if you want) and add a restful API "/promotions/id/cancel" to modify it. So how about this, I would assign the "status" issue to myself and modify the function "is_available" into an attribute. Then you can write the "cancel" route as well as the "find_the_best" route.

**Comment by ReedyChen** [comment]
Great, you can modify the 'available' into an attribute, call it whatever you want. And I will add a route to it once it is finished. 
My only concern is, once the from_date/to_date is modified, the attribute 'available' should also be changed as well, unlike right now every time we check whether a promotion is available, we just compare it by its dates. So that I think there should be a way to constantly update the attribute or at least every time when we tried to get the attribute, we recalculated according to the dates.

**Comment by HerlinHe** [comment]
If we still use two dates to judge whether a promotion is valid or not, then we come back to the previous question, do we need a new attribute to represent the availability? The scenario we need an attribute is that we use this attribute "availability" as the only flag representing if a promotion is valid. Even when a promotion is in the right time range, we can simply mark it "unavailable" if we want to cancel it. And every queried promotion whose time range does not include the current time should be marked "unavailable" too.

How about this. Since the requirement of sprint 2 is to add a stateful query like "promotions/id/cancel", then there is a simple way to implement this without changing our model. That is modifying the "to_date" to the day before "today", then it will automatically become "expired". If you agree with this, then we can delete the issue about the "state model" and focus on the route part. I have confirmed with TA that we don't need to add an attribute, as long as we can achieve such a query with existing attributes.

**Comment by ReedyChen** [comment]
If TA said it is workable, then I agree with this change. You can revert the merge and I will implement the cancel route

**Pull request closed without merging**
