### PR TITLE
add honcho

### PR DESCRIPTION
**Pull request by HerlinHe**

### CODE REVIEW

**Comment by ahbbzong** [comment]
I generated an ElephantDB for our cloud as a database. Are you going to use cloudant or you have other concerns about cloud delopyment?

**Comment by HerlinHe** [comment]
Sorry, I don’t get your point. Is what you are talking about related to this issue, adding honcho?

**Comment by ahbbzong** [comment]
I saw you add cloudant username and password for dot-env-example. So I was thinking if you want to do anything on cloudant.

**Comment by HerlinHe** [comment]
I just copy that from professor’s demo. So is there any reason to use a different DB? Because if not, we can make fewer mistakes doing what professor taught I think. If you think that is necessary, you can delete these lines and won’t break the honcho part in my perspective.

**Comment by ahbbzong** [comment]
Professor recommends us to use Elephant DB. Just check the slack about the TA's comment. So for our application, I switched the cloud to elephant DB

**Comment by HerlinHe** [comment]
Fantastic. Sorry, I haven’t check slack these days. Then I’ll delete these lines later today. Could you please check it tonight and approve the merge? I also completed the BDD part and after this being merged I can submit a new pr.

**Comment by ahbbzong** [comment]
No problem！

**Pull request merged**
